"""Add Deal model

Revision ID: 48b209f7e736
Revises: 9580582cc6b8
Create Date: 2025-12-28 18:37:02.500673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b209f7e736'
down_revision: Union[str, Sequence[str], None] = '9580582cc6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Deal title/name'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Associated customer ID'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Deal owner (sales user) ID'),
    sa.Column('stage', sa.Enum('PROSPECTING', 'QUALIFICATION', 'PROPOSAL', 'NEGOTIATION', 'CLOSED_WON', 'CLOSED_LOST', name='dealstage'), nullable=False, comment='Current stage in sales pipeline'),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False, comment='Deal value in currency'),
    sa.Column('expected_close_date', sa.Date(), nullable=True, comment='Expected closing date'),
    sa.Column('probability', sa.Integer(), nullable=False, comment='Win probability (0-100)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_customer_id'), 'deals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deals_id'), 'deals', ['id'], unique=False)
    op.create_index(op.f('ix_deals_owner_id'), 'deals', ['owner_id'], unique=False)
    op.create_index(op.f('ix_deals_stage'), 'deals', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_owner_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_customer_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
