"""Add Task model

Revision ID: 8e417cc46126
Revises: 48b209f7e736
Create Date: 2025-12-28 18:53:14.985701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e417cc46126'
down_revision: Union[str, Sequence[str], None] = '48b209f7e736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False, comment='Task title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Task description'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False, comment='Assigned user ID'),
    sa.Column('created_by_id', sa.Integer(), nullable=False, comment='User who created the task'),
    sa.Column('related_type', sa.Enum('LEAD', 'CUSTOMER', 'DEAL', name='relatedentitytype'), nullable=True, comment='Type of related entity'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='ID of the related entity'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Task due date'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False, comment='Task priority'),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', name='taskstatus'), nullable=False, comment='Task status'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
