"""Add Lead and LeadNote models

Revision ID: 8f7f5f072410
Revises: c2c5ce6f05f2
Create Date: 2025-12-28 18:15:05.389716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7f5f072410'
down_revision: Union[str, Sequence[str], None] = 'c2c5ce6f05f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="Lead's full name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="Lead's email address"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment="Lead's phone number"),
    sa.Column('source', sa.Enum('WEBSITE', 'REFERRAL', 'CAMPAIGN', 'DIRECT', 'OTHER', name='leadsource'), nullable=False, comment='Lead source'),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'PROPOSAL', 'WON', 'LOST', name='leadstatus'), nullable=False, comment='Current status in sales pipeline'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True, comment='Assigned sales person ID'),
    sa.Column('created_by_id', sa.Integer(), nullable=False, comment='User who created the lead'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_assigned_to_id'), 'leads', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('lead_notes',
    sa.Column('lead_id', sa.Integer(), nullable=False, comment='Associated lead ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who created the note'),
    sa.Column('note_text', sa.Text(), nullable=False, comment='Note content'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_id'), 'lead_notes', ['id'], unique=False)
    op.create_index(op.f('ix_lead_notes_lead_id'), 'lead_notes', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_notes_lead_id'), table_name='lead_notes')
    op.drop_index(op.f('ix_lead_notes_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
