"""Add Customer and CustomerInteraction models

Revision ID: 9580582cc6b8
Revises: 8f7f5f072410
Create Date: 2025-12-28 18:26:53.889110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9580582cc6b8'
down_revision: Union[str, Sequence[str], None] = '8f7f5f072410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
