"""Add Customer and CustomerInteraction models

Revision ID: 9580582cc6b8
Revises: 8f7f5f072410
Create Date: 2025-12-28 18:26:53.889110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9580582cc6b8'
down_revision: Union[str, Sequence[str], None] = '8f7f5f072410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="Customer's full name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="Customer's email address"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment="Customer's phone number"),
    sa.Column('company', sa.String(length=255), nullable=True, comment="Customer's company name"),
    sa.Column('lead_id', sa.Integer(), nullable=True, comment='Original lead ID (if converted)'),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True, comment='Assigned account manager ID'),
    sa.Column('created_by_id', sa.Integer(), nullable=False, comment='User who created the customer record'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_customers_assigned_to_id'), 'customers', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)

    op.create_table('customer_interactions',
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Associated customer ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User who logged the interaction'),
    sa.Column('interaction_type', sa.Enum('CALL', 'EMAIL', 'MEETING', 'NOTE', name='interactiontype'), nullable=False, comment='Type of interaction'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Interaction subject/title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Interaction details'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_assigned_to_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
